# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: INTISA Servicios Profesionales
email: atencionalcliente@intisa.com
description: Somos una consultora tecnológica cuyo objetivo es ofrecer servicios de calidad a nuestros clientes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: INTISA Servicios Profesionales
company_name_sort: INTISA
company_tax: B82592692
address_line: C/ Llull 321, 08019 - Barcelona
telephone_number: (+34) 93 551 45 46
company_email: atencionalcliente@intisa.com
google_map: https://maps.app.goo.gl/TjsHSYs9oMjV3nAN8
custom_service: atencionalcliente@intisa.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
